INSERT INTO Pracownicy (IMIE_PRACOWNIKA,NAZWISKO_PRACOWNIKA,MAIL,DATA_URODZENIA) VALUES ('Jan','Kowalski','kowal@co.net','1.2.1993');
INSERT INTO Pracownicy (IMIE_PRACOWNIKA,NAZWISKO_PRACOWNIKA,MAIL,DATA_URODZENIA) VALUES ('Mateusz','Kloc','kloc@co.net','11.3.2000');
INSERT INTO Pracownicy (IMIE_PRACOWNIKA,NAZWISKO_PRACOWNIKA,MAIL,DATA_URODZENIA) VALUES ('Agata','Kilo','kiloaga@co.net','11.5.1999');
INSERT INTO Pracownicy (IMIE_PRACOWNIKA,NAZWISKO_PRACOWNIKA,MAIL,DATA_URODZENIA) VALUES ('Damian','Huba','hubabuba@no.com','1.1.1991');
INSERT INTO Pracownicy (IMIE_PRACOWNIKA,NAZWISKO_PRACOWNIKA,MAIL,DATA_URODZENIA) VALUES ('Patrycja','Vita','vita@no.com','1.1.1981');